services:
  shop-backend:
    container_name: shop-backend
    build:
      context: spring-shop
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./spring-shop:/app
  # postgres:
  #   image: 'postgres:latest'
  #   environment:
  #     - 'POSTGRES_DB=mydatabase'
  #     - 'POSTGRES_PASSWORD=secret'
  #     - 'POSTGRES_USER=myuser'
  #   ports:
  #     - '5432'
  # redis:
  #   image: 'redis:latest'
  #   ports:
  #     - '6379'
